### ISSUE TITLE
Built-in components to render notifications in react-native?

### ISSUE THREAD

**Issue by y9m** [knocklabs/javascript#128]
Are there any components to render the notifications in react-native? I know the react library has `NotificationIconButton` and `NotificationFeedPopover`, but it doesn't seem like react-native has a good way to render the notifications in-app. Right now I'm manually navigating the response to dig up `item.blocks[0].rendered` (which works but throws a type error) and using `RenderHTML` to display the html. Built-in components for react-native would help a lot in this respect.

![image](https://github.com/knocklabs/javascript/assets/38928651/06643f17-3bb9-4c25-89cf-b023d5ad1ec3)

**Comment by matgar26** [comment]
Thank you for your feedback, @y9m. We are aware of the need for built-in components to render notifications within our React Native SDK, similar to what we offer in our React library with components like `NotificationIconButton` and `NotificationFeedPopover`. We're excited to let you know that development of these built-in components for all of our mobile SDKs, including React Native, is underway and will be available soon.

In the interim, regarding the TypeScript error you're encountering, it's likely due to our `ContentBlock` objects varying in type—specifically, `MarkdownContentBlock`, `TextContentBlock`, and `ButtonSetContentBlock`. Only the Markdown and Text content blocks include a `rendered` property, whereas the Button Set does not, which can lead to type errors when not handled explicitly.

To assist with this, you can implement a type guard to safely access the `rendered` property where applicable. Here’s how you can integrate this into your current setup:

```typescript
function hasRenderedProperty(block: ContentBlock): block is TextContentBlock | MarkdownContentBlock {
  return 'rendered' in block;
}

items.map((item: FeedItem) => (
  item.blocks.map(block => 
    hasRenderedProperty(block) && (
      <View key={item.id} style={{ marginTop: 16 }}>
        <RenderHtml contentWidth={400} source={{ html: block.rendered }} />
      </View>
    )
  )
))
```

This approach ensures that you are only attempting to render HTML content from blocks that actually contain the `rendered` field, thereby avoiding any type errors and enhancing the robustness of your application's notification rendering logic.

We appreciate your patience and are committed to enhancing the React Native SDK to better meet your needs. Stay tuned for updates!
